name: Checks
on: [push, pull_request]
jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8] # , 11, 17, 21
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'gradle'
    - name: Install language packs
      run: |
        sudo apt-get update
        sudo apt-get install language-pack-cs
    - name: Accept third party licence
      env:
        ACCEPT_LICENCE: ${{ secrets.ACCEPT_LICENCE }}
      if: env.ACCEPT_LICENCE == 'true'
      run: ./accept-third-party-license.sh
    - name: Build with Gradle
      run: ./gradlew build -x test # Disable general test, only run testsuites
